apiVersion: v1
kind: Pod
metadata:
  name: quiz-vue-app
spec:
  containers:
  - name: quiz-vue
    image: quiz-roulette/quiz-vue-js:latest
    env:
    - name: VUE_APP_QUESTION_BANK_API
      value: http://question-bank:80
    ports:
    - containerPort: 80
